### ISSUE TITLE
Scons compiling error: fatal error: header.h: No such file or directory

### ISSUE THREAD

**Issue by zhangysh1995** [SLACKHA/accelerInt#5]
````
zhangysh1995@ubuntu-zhangyushao:~/data/scons/accelerInt$ scons
scons: Reading SConscript files ...
INFO: SCons is using the following Python interpreter: /usr/bin/python
CUDA not found, no GPU integrators will be built
scons: done reading SConscript files.
scons: Building targets ...
gcc -o generic/cvodes/release/read_initial_conditions.o -c -std=c99 -m64 -O3 -funroll-loops -Wno-inline -mtune=native -fopenmp -DCVODES -Igeneric -Imechanism -Icvodes -Igeneric/cvodes/release/usr/local/include generic/cvodes/release/read_initial_conditions.c
generic/cvodes/release/read_initial_conditions.c:10:20: fatal error: header.h: No such file or directory
compilation terminated.
scons: *** [generic/cvodes/release/read_initial_conditions.o] Error 1
scons: building terminated because of errors.
````

**Comment by arghdos** [comment]
@zhangysh1995 Hi there!

Could you describe the initial value problem(s) you're trying to use accelerInt to solve?
The exact definition of the `header.h` file you need will depend on this.

To see more information, check the [Van Der Pol](http://slackha.github.io/accelerInt/vdp.html) example, in particular the [sample header.h](http://slackha.github.io/accelerInt/header_8h_source.html) file bundled with it

**Comment by zhangysh1995** [comment]
@arghdos I'm testing a project configuration utility on random projects from github, and came across this error. I think it's better to add some instruction in the README or default implementation for the `header.h`. Thank you all the same. Closed.
